name: Static Analysis

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    name: Larastan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Run Larastan
        run: vendor/bin/phpstan analyse --memory-limit=2G